services:
  nats-server:
    container_name: nats2
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
      - 8080:8080
    image: nats:2.10.7-alpine3.18
    command: ["-c", "/tmp/nats.conf"]
    volumes:
      - ./nats.conf:/tmp/nats.conf

  postgres:
    container_name: database
    image: postgres:14
    ports:
      - 5431:5432
    volumes:
      - appDbVolume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DATABASE=appdb

volumes:
 appDbVolume: